os: linux
dist: bionic

language: python
cache: pip

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

python:
  - "3.6"
  - "3.7"

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
   - pip install -r requirements.txt
   - pip install flake8

script:
    - pytest -v
    - flake8 . --exit-zero
